### ISSUE TITLE
使用官方插件 @vitejs/plugin-react

### ISSUE THREAD

**Issue by ModyQyW** [spark-build/vite-plugin-react-auto-config#2]
目前 react 已经有官方插件 [@vitejs/plugin-react](https://github.com/vitejs/vite/tree/main/packages/plugin-react#readme)，是否考虑基于官方插件改进呢？

**Comment by atzcl** [comment]
非常好的建议，不过看了下源码，发现还是用的 `babel` ，目前可能是考虑用 `swc` 来处理这部分，另外 `react-router@v6` 也是最后一个 beta 了，有不少改动，到时候一并更新上来

**Comment by atzcl** [comment]
@ModyQyW  已更新至 `@vitejs/plugin-react`，并且适配了 `react-router@v6.x`，另外针对 `router` 增加（借鉴）了类似 `vue-router-next` 的全局前置路由守卫、后置钩子、编程式路由等

`swc` 部分在等待 https://github.com/iheyunfei/vite-on-swc 这个插件成熟了就可以了

**Comment by ModyQyW** [comment]
`swc` 部分也可以看一下 [unplugin-swc](https://github.com/egoist/unplugin-swc)

**Comment by atzcl** [comment]
> `swc` 部分也可以看一下 [unplugin-swc](https://github.com/egoist/unplugin-swc)

`unplugin-swc` 跟 `vite-on-swc` 差不多，不过 `vite-on-swc` 还拓展了 HMR，这样功能是对齐了 `@vitejs/plugin-react`
